services:
  backend:
    container_name: backend
    image: node:18-alpine
    restart: always
    ports:
      - protocol: tcp
        published: ${BACKEND_PORT:-8080}
        target: 3000
    volumes:
      - type: bind
        source: ./backend
        target: /app/dist
    working_dir: /app
    command: [ 'node index' ]
    user: "${USER_ID:-0}:${GROUP_ID:-0}"
    networks:
      - backend

  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local:latest
    restart: always
    ports:
      - protocol: tcp
        published: ${DYNAMODB_PORT:-8000}
        target: 8000
    volumes:
      - type: volume
        source: dynamodb
        target: /home/dynamodblocal/data
    command: [ '-jar', 'DynamoDBLocal.jar', '-dbPath', '/home/dynamodblocal/data', '-sharedDb' ]
    user: "${USER_ID:-0}:${GROUP_ID:-0}"
    networks:
      - backend

  dynamodb-admin:
    container_name: dynamodb-admin
    build:
      context: ./docker/dynamodb-admin
    restart: always
    ports:
      - protocol: tcp
        published: ${DYNAMODB_ADMIN_PORT:-8001}
        target: 8001
    networks:
      - backend
      - frontend
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    command: [ 'dynamodb-admin' ]

volumes:
  dynamodb: {}

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
