openapi: 3.0.0
info:
  title: Vigilante
  description: |
    Software abierto para fiscalizar elecciones. Conteo de votos, anotaciones y registro de impugnaciones a nivel distrito, municipio, centro y mesa. Promoviendo transparencia y participación ciudadana en procesos electorales.
  license:
    name: GPL 3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html#license-text
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/jatitoam/vigilante/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: health
  description: Health Status
paths:
  /health:
    get:
      tags:
      - health
      summary: Display the health status of the project
      operationId: health
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Health'
  /login:
    post:
      tags:
      - login
      summary: Retorna el token si las credenciales son validas
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Login'
  /fiscales:
    get:
      tags:
      - fiscales
      summary: Despliega la información asignada al fiscal
      operationId: fiscales
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fiscal'
components:
  schemas:
    Health:
      type: object
      properties:
        health:
          type: string
        projectName:
          type: string
        projectVersion:
          type: string
    Login:
      type: object
      properties:
        token:
          type: string
    Fiscal:
      type: array
      items:
        type: object
        properties:
          tipo:
            type: string
          nombre:
            type: string
          codigo:
            type: string
