openapi: 3.0.0
info:
  title: Vigilante
  description: |
    Software abierto para fiscalizar elecciones. Conteo de votos, anotaciones y registro de impugnaciones a nivel distrito, municipio, centro y mesa. Promoviendo transparencia y participación ciudadana en procesos electorales.
  license:
    name: GPL 3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html#license-text
  version: 1.0.0
paths:
  /health:
    get:
      summary: Display the health status of the project
      operationId: health
      responses:
        "200":
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Health'
  /login:
    post:
      summary: Retorna el token si las credenciales son validas
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Login'
  /fiscales:
    get:
      summary: Despliega las fiscalías disponibles del usuario ingresado en su JWT
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fiscal'
  /partidos:
    get:
      summary: Despliega los partidos disponibles
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Partido'
  /recuentos:
    put:
      summary: Actualiza el recuento de votos de una mesa, centro, municipio o departamento
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tipo:
                  type: string
                  enum: [mesa, centro, municipio, departamento]
                uuid:
                  type: string
                  format: uuid
                partidos:
                  type: array
                  items:
                    type: object
                    properties:
                      partido_uuid:
                        type: string
                        format: uuid
                      votos:
                        type: integer
      responses:
        "201":
          description: Operación exitosa
        "404":
          description: No se encontró la mesa, centro, municipio o departamento
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Health:
      type: object
      properties:
        health:
          type: string
        projectName:
          type: string
        projectVersion:
          type: string
    Login:
      type: object
      properties:
        token:
          type: string
          format: JWT
    Fiscal:
      type: array
      items:
        type: object
        properties:
          uuid:
            type: string
            format: uuid
          tipo:
            type: string
            enum: [mesa, centro, municipio, departamento]
          nombre:
            type: string
          codigo:
            type: string
    Partido:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        nombre:
          type: string
        color:
          type: string